/**
 * dsh-sync-tool — Host half.
 *
 * Owns two settings namespaces, which are the whole Host<->browser contract:
 *
 *  - `sync-tool`        user configuration (work areas, triggers, commands),
 *                       registered through `installSection` so the browser card
 *                       pairs with it by namespace key.
 *  - `sync-tool-status` Host-published runtime state (per-area result, capped
 *                       history). The card binds this scope read-only; no card
 *                       claims the key, so the Plugins tab renders no second
 *                       card for it.
 *
 * The git engine and the `turn/end` hook are added in later stages; see PLAN.md.
 */
import { statSync } from 'node:fs'
import { isAbsolute } from 'node:path'

import z from '@deepseek-ai/schemastery'

/** Cordis plugin name (the loader row's `name` is the module specifier). */
export const name = 'sync-tool'

/** User-configuration namespace; the browser card claims this key. */
export const SYNC_NAMESPACE = 'sync-tool'

/** Host-published status namespace; consumed read-only by the card. */
export const STATUS_NAMESPACE = 'sync-tool-status'

/** Status values one work area can report. */
export const AREA_STATUS = Object.freeze(['idle', 'validating', 'syncing', 'ok', 'conflict', 'error'])

/** Sync directions. */
export const DIRECTIONS = Object.freeze(['both', 'push', 'pull'])

/** One work area: the local folder and the remote it syncs with. */
const AreaSchema = z.object({
  /** Stable identity; generated by the card, never reused. */
  id: z.string().required(),
  /** Display name; falls back to the folder's basename in the UI. */
  name: z.string().default(''),
  /** Absolute local folder path. */
  path: z.string().required(),
  /** Remote git URL; empty means "not configured yet". */
  remote: z.string().default(''),
  /** Branch tracked on the remote. */
  branch: z.string().default('main'),
  /** Credential reference name resolved through ctx.credentials. */
  credentialRef: z.string().default(''),
  /** Sync direction. */
  direction: z.union([...DIRECTIONS]).default('both'),
  /** Whether automatic sync includes this area. */
  enabled: z.boolean().default(true),
  /** Commit local changes before pulling/pushing. */
  autoCommit: z.boolean().default(true),
  /** Extra ignore patterns on top of the built-in set. */
  extraIgnores: z.array(z.string()).default([]),
  /** Treat matching paths as fatal to commit (safety net). */
  guardSensitive: z.boolean().default(true),
})

/**
 * Resolved configuration, layered as schema defaults, then the composition
 * row's `config`, then the user document section.
 */
export const Config = z.object({
  /** Master switch for every automatic sync. */
  enabled: z.boolean().default(true),
  /** Sync the work areas a finished turn touched. */
  syncOnTurnEnd: z.boolean().default(true),
  /** Run one pull/sync for every enabled area when the Host starts. */
  syncOnStartup: z.boolean().default(false),
  /** Coalescing window for bursty turn boundaries, in milliseconds. */
  debounceMs: z.natural().default(5000),
  /** Commit message template; `{host}`, `{time}` and `{turn}` are substituted. */
  commitMessageTemplate: z.string().default('dsh-sync: {host} {time} (turn {turn})'),
  /** How many history entries the status namespace keeps. */
  historyLimit: z.natural().default(20),
  /** Configured work areas. */
  areas: z.array(AreaSchema).default([]),
  /**
   * Command channel: the card bumps `token` to ask the Host to act. Settings is
   * the only documented browser->Host write channel for an out-of-tree plugin,
   * so commands ride a field the Host watches rather than a private Remote.
   */
  request: z.object({
    /** Monotonic request id; a change is what the Host acts on. */
    token: z.natural().default(0),
    /** Target area for `syncArea`; empty targets every enabled area. */
    areaId: z.string().default(''),
    /** `none` is the idle value. */
    kind: z.union(['none', 'sync']).default('none'),
    /** When the card issued the request. */
    at: z.natural().default(0),
  }).default({ token: 0, areaId: '', kind: 'none', at: 0 }),
})

/** One history entry. */
const HistoryEntrySchema = z.object({
  at: z.natural().required(),
  areaId: z.string().required(),
  ok: z.boolean().required(),
  summary: z.string().default(''),
})

/** One area's latest observed state. */
const AreaStatusSchema = z.object({
  id: z.string().required(),
  status: z.union([...AREA_STATUS]).default('idle'),
  at: z.natural().default(0),
  detail: z.string().default(''),
  head: z.string().default(''),
  ahead: z.natural().default(0),
  behind: z.natural().default(0),
})

/** Host-published status document. */
export const StatusConfig = z.object({
  /** Bumped on every publish so the card can tell snapshots apart. */
  revision: z.natural().default(0),
  /** Whether a sync pass is in flight. */
  running: z.boolean().default(false),
  /** Timestamp of the last publish. */
  updatedAt: z.natural().default(0),
  /** Folder validation results, keyed by area id. */
  areas: z.array(AreaStatusSchema).default([]),
  /** Most recent results, newest last, capped at `historyLimit`. */
  history: z.array(HistoryEntrySchema).default([]),
})

/** Why one area's folder is unusable, or undefined when it is fine. */
function folderProblem(path) {
  if (typeof path !== 'string' || path.trim() === '') return '路径为空 / empty path'
  if (!isAbsolute(path)) return '必须是绝对路径 / not an absolute path'
  let stats
  try {
    stats = statSync(path)
  } catch {
    return '目录不存在或不可访问 / does not exist or is not accessible'
  }
  if (!stats.isDirectory()) return '不是目录 / not a directory'
  return undefined
}

/**
 * Mount the Host half.
 * @param ctx - host cordis context.
 * @param config - schema-resolved configuration for this row.
 */
export function apply(ctx, config) {
  // The authoritative configuration thunk: the resolved settings scope while a
  // provider is attached, the composition entry otherwise.
  let resolveConfig = () => config

  // Status scope, filled in when the settings provider is present.
  let publish = () => {}
  let publishedRevision = 0

  ctx.inject(['settings'], (settingsCtx) => {
    const settings = settingsCtx.settings

    settings.installSection(ctx, SYNC_NAMESPACE, Config, config, {
      setSource: (current) => { resolveConfig = current },
      onChange: () => { publish() },
    })

    // The status namespace is Host-owned: published wholesale, never merged,
    // because `update` deep-merges and would splice lists element-wise.
    const statusScope = settings.register(STATUS_NAMESPACE, StatusConfig, {
      base: { revision: 0, running: false, updatedAt: 0, areas: [], history: [] },
    })

    /** Compute and write the status document. */
    publish = () => {
      const current = resolveConfig() ?? {}
      const areas = Array.isArray(current.areas) ? current.areas : []
      const previous = statusScope.get() ?? {}
      const kept = new Map(
        (Array.isArray(previous.areas) ? previous.areas : []).map(entry => [entry.id, entry]),
      )

      const reported = areas.map((area) => {
        const problem = folderProblem(area.path)
        const before = kept.get(area.id)
        // A folder problem is a fresh fact and wins; otherwise keep what the
        // engine last reported for this area.
        if (problem !== undefined) {
          return { id: area.id, status: 'error', at: Date.now(), detail: problem, head: '', ahead: 0, behind: 0 }
        }
        return before ?? { id: area.id, status: 'idle', at: 0, detail: '', head: '', ahead: 0, behind: 0 }
      })

      publishedRevision += 1
      void statusScope.replace({
        revision: publishedRevision,
        running: previous.running === true,
        updatedAt: Date.now(),
        areas: reported,
        history: Array.isArray(previous.history) ? previous.history : [],
      }).catch((error) => {
        console.warn(`[sync-tool] status publish failed: ${error instanceof Error ? error.message : String(error)}`)
      })
    }

    publish()
  })

  console.log(`[sync-tool] host half loaded (namespaces "${SYNC_NAMESPACE}", "${STATUS_NAMESPACE}")`)
}
