/**
 * dsh-sync-tool — Host half.
 *
 * Owns two settings namespaces, which are the whole Host<->browser contract:
 *
 *  - `sync-tool`        user configuration (work areas, triggers, commands),
 *                       registered through `installSection` so the browser card
 *                       pairs with it by namespace key.
 *  - `sync-tool-status` Host-published runtime state (per-area result, capped
 *                       history). The card binds this scope read-only; no card
 *                       claims the key, so the Plugins tab renders no second
 *                       card for it.
 *
 * Settings is also the command channel: an out-of-tree plugin has no generated
 * Remote namespace, so the card bumps `request.token` and this half watches the
 * committed value. The git engine lives in `./git.js`; session records are
 * exported into and imported from the work area by `./sessions.js`, and the
 * device-switch notice model-side lives in `./notice.js`.
 */
import { statSync } from 'node:fs'
import { isAbsolute } from 'node:path'

import z from '@deepseek-ai/schemastery'

import { buildCommitMessage, GitEngine, normalizePath, pathContains } from './git.js'
import { installDeviceNotice } from './notice.js'
import { areaFromManifest, baseName, MANIFEST_NAME, readManifest, writeManifest } from './portable.js'
import { archiveDir, COMPRESSIONS, CWD_POLICIES, SESSIONS_DIR, SessionSync } from './sessions.js'

/** Cordis plugin name (the loader row's `name` is the module specifier). */
export const name = 'sync-tool'

/** User-configuration namespace; the browser card claims this key. */
export const SYNC_NAMESPACE = 'sync-tool'

/** Host-published status namespace; consumed read-only by the card. */
export const STATUS_NAMESPACE = 'sync-tool-status'

/** Status values one work area can report. */
export const AREA_STATUS = Object.freeze(['idle', 'validating', 'syncing', 'ok', 'conflict', 'error'])

/** Sync directions. */
export const DIRECTIONS = Object.freeze(['both', 'push', 'pull'])

/** Command kinds the card may request. */
export const REQUEST_KINDS = Object.freeze(['none', 'sync', 'import'])

/** One work area: the local folder and the remote it syncs with. */
const AreaSchema = z.object({
  /** Stable identity; generated by the card, never reused. */
  id: z.string().required(),
  /** Display name; falls back to the folder's basename in the UI. */
  name: z.string().default(''),
  /** Absolute local folder path. */
  path: z.string().required(),
  /** Remote git URL; empty means "not configured yet". */
  remote: z.string().default(''),
  /** Branch tracked on the remote. */
  branch: z.string().default('main'),
  /** Credential reference name resolved through ctx.credentials. */
  credentialRef: z.string().default(''),
  /** Sync direction. */
  direction: z.union([...DIRECTIONS]).default('both'),
  /** Whether automatic sync includes this area. */
  enabled: z.boolean().default(true),
  /** Commit local changes before pulling/pushing. */
  autoCommit: z.boolean().default(true),
  /** Extra ignore patterns on top of the built-in set. */
  extraIgnores: z.array(z.string()).default([]),
  /** Refuse to commit when a sensitive file is staged. */
  guardSensitive: z.boolean().default(true),
  /**
   * What to do when the folder sits inside another checkout — common when the
   * home directory is itself a repository and the DSH assets live beneath it.
   * `init` creates an independent nested repository; `refuse` reports an error.
   */
  nestedRepos: z.union(['init', 'refuse']).default('init'),
})

/**
 * Session-record synchronisation, layered under the same master switch.
 *
 * `cwdPolicy` defaults to `keep` on purpose: the shipped presets render
 * `{{cwd}}` into the system prompt, so rewriting the recorded working directory
 * would change surface node 0 and drop the provider's prefix cache from the
 * first token. Keeping it means an imported session continues exactly where the
 * other machine left off, as long as the work area uses the same absolute path.
 */
const SessionsSchema = z.object({
  /** Whether sessions travel with the work area. */
  enabled: z.boolean().default(true),
  /** Subdirectory of the work area that holds the archives. */
  dir: z.string().default(SESSIONS_DIR),
  /** Archive encoding: compact `zstd`, or `none` for reviewable plain text. */
  compression: z.union([...COMPRESSIONS]).default('zstd'),
  /** Include sessions whose working directory is a subdirectory of the area. */
  includeDescendants: z.boolean().default(true),
  /** Per area, how many of the newest in-scope sessions to synchronise. */
  maxSessions: z.natural().default(200),
  /** Skip a single archive larger than this many bytes; 0 means no limit. */
  maxBytes: z.natural().default(0),
  /** What to do when the recorded working directory does not exist here. */
  cwdPolicy: z.union([...CWD_POLICIES]).default('keep'),
  /** Tell the model, invisibly, that this session came from another machine. */
  hintOnDeviceSwitch: z.boolean().default(true),
  /** Machine-local bookkeeping file; empty uses `$DSH_HOME/sync-tool/sessions.json`. */
  statePath: z.string().default(''),
})

const SESSION_DEFAULTS = {
  enabled: true,
  dir: SESSIONS_DIR,
  compression: 'zstd',
  includeDescendants: true,
  maxSessions: 200,
  maxBytes: 0,
  cwdPolicy: 'keep',
  hintOnDeviceSwitch: true,
  statePath: '',
}

/**
 * Resolved configuration, layered as schema defaults, then the composition
 * row's `config`, then the user document section.
 */
export const Config = z.object({
  /** Master switch for every automatic sync. */
  enabled: z.boolean().default(true),
  /** Sync the work areas a finished turn touched. */
  syncOnTurnEnd: z.boolean().default(true),
  /** Run one pass over every enabled area when the Host starts. */
  syncOnStartup: z.boolean().default(false),
  /**
   * Sync every enabled area at a turn boundary instead of only those whose
   * folder contains the session's working directory.
   */
  syncAllOnTurnEnd: z.boolean().default(false),
  /** Coalescing window for bursty turn boundaries, in milliseconds. */
  debounceMs: z.natural().default(5000),
  /** Commit message template; `{host}`, `{time}` and `{turn}` are substituted. */
  commitMessageTemplate: z.string().default('dsh-sync: {host} {time} (turn {turn})'),
  /**
   * Identity for automatic commits, used **only** when the machine has no git
   * identity of its own. Blank falls back to `dsh-sync@<hostname>`; set both
   * fields to author this machine's sync commits as yourself.
   */
  commitIdentity: z.object({
    name: z.string().default(''),
    email: z.string().default(''),
  }).default({ name: '', email: '' }),
  /** How many history entries the status namespace keeps. */
  historyLimit: z.natural().default(20),
  /** Session-record synchronisation. */
  sessions: SessionsSchema.default(SESSION_DEFAULTS),
  /** Configured work areas. */
  areas: z.array(AreaSchema).default([]),
  /**
   * Command channel: the card bumps `token` to ask the Host to act. Settings is
   * the only documented browser->Host write channel for an out-of-tree plugin,
   * so commands ride a field the Host watches rather than a private Remote.
   */
  request: z.object({
    /** Monotonic request id; a change is what the Host acts on. */
    token: z.natural().default(0),
    /** Target area for a sync; empty targets every enabled area. */
    areaId: z.string().default(''),
    /** `none` is the idle value. */
    kind: z.union([...REQUEST_KINDS]).default('none'),
    /** When the card issued the request. */
    at: z.natural().default(0),
  }).default({ token: 0, areaId: '', kind: 'none', at: 0 }),
})

/** One history entry. */
const HistoryEntrySchema = z.object({
  at: z.natural().required(),
  areaId: z.string().required(),
  ok: z.boolean().required(),
  summary: z.string().default(''),
})

/** One area's latest observed state. */
const AreaStatusSchema = z.object({
  id: z.string().required(),
  status: z.union([...AREA_STATUS]).default('idle'),
  at: z.natural().default(0),
  detail: z.string().default(''),
  head: z.string().default(''),
  ahead: z.natural().default(0),
  behind: z.natural().default(0),
})

/** Host-published status document. */
export const StatusConfig = z.object({
  /** Bumped on every publish so the card can tell snapshots apart. */
  revision: z.natural().default(0),
  /** Whether a sync pass is in flight. */
  running: z.boolean().default(false),
  /** Timestamp of the last publish. */
  updatedAt: z.natural().default(0),
  /** Latest state per configured area. */
  areas: z.array(AreaStatusSchema).default([]),
  /** Most recent results, newest last, capped at `historyLimit`. */
  history: z.array(HistoryEntrySchema).default([]),
})

/** Why one area's folder is unusable, or undefined when it is fine. */
export function folderProblem(path) {
  if (typeof path !== 'string' || path.trim() === '') return '路径为空 / empty path'
  if (!isAbsolute(path)) return '必须是绝对路径 / not an absolute path'
  let stats
  try {
    stats = statSync(path)
  } catch {
    return '目录不存在或不可访问 / does not exist or is not accessible'
  }
  if (!stats.isDirectory()) return '不是目录 / not a directory'
  return undefined
}

/**
 * Mount the Host half.
 * @param ctx - host cordis context.
 * @param config - schema-resolved configuration for this row.
 */
export function apply(ctx, config) {
  // The authoritative configuration thunk: the resolved settings scope while a
  // provider is attached, the composition entry otherwise.
  let resolveConfig = () => config

  /** Runtime state the engine writes and the status publisher reads. */
  const runtime = {
    running: false,
    areas: new Map(),
    sessions: new Map(),
    history: [],
    revision: 0,
    statusScope: undefined,
    seenRequestToken: -1,
    disposed: false,
  }

  const engine = new GitEngine(ctx, { log: () => {} })

  /** Session archive engine: one machine-local state file, shared by both halves. */
  const sessionSync = new SessionSync(ctx, { log: () => {} })

  /** Serialize every pass: one git sequence at a time, globally. */
  let queue = Promise.resolve()

  const warn = (message) => { console.warn(`[sync-tool] ${message}`) }

  /** Read the configured areas, normalized. */
  const configuredAreas = () => {
    const current = resolveConfig() ?? {}
    return Array.isArray(current.areas) ? current.areas : []
  }

  /** Read the resolved session-synchronisation block. */
  const sessionConfig = () => {
    const block = (resolveConfig() ?? {}).sessions
    return block !== null && typeof block === 'object' ? block : {}
  }

  /**
   * One session step of a sync pass. It never throws: a session problem must
   * not be able to fail the git pass it rides along with.
   * @param kind - `export` before the commit, `import` after the merge.
   * @param area - the work area being synced.
   * @param signal - the pass cancellation.
   * @returns status fragments to append to the area detail.
   */
  const runSessionStep = async (kind, area, signal) => {
    const config = sessionConfig()
    if (config.enabled === false) return []
    const summary = kind === 'export'
      ? await sessionSync.exportArea(area, config, signal)
      : await sessionSync.importArea(area, config, signal)
    const entry = runtime.sessions.get(area.id) ?? { notes: [], at: 0 }
    if (Array.isArray(summary.notes)) entry.notes.push(...summary.notes)
    entry.at = Date.now()
    runtime.sessions.set(area.id, entry)
    const parts = []
    if (kind === 'export' && summary.exported > 0) parts.push(`会话↑${summary.exported}`)
    if (kind === 'import' && summary.imported > 0) parts.push(`会话↓${summary.imported}`)
    if (kind === 'import' && summary.appended > 0) parts.push(`会话并入${summary.appended}`)
    if (summary.conflicts > 0) parts.push(`会话冲突${summary.conflicts}`)
    if (summary.failed > 0) parts.push(`会话失败${summary.failed}`)
    return parts
  }

  // The device-switch notice reads the import records this machine keeps, so it
  // is registered once, globally, and decides per assembled session.
  installDeviceNotice(ctx, {
    imports: () => sessionSync.imports(),
    enabled: () => sessionConfig().hintOnDeviceSwitch !== false,
    archiveDir: (record) => {
      const area = configuredAreas().find(candidate => candidate.id === record?.areaId)
      return area === undefined ? '' : archiveDir(area.path, sessionConfig().dir)
    },
  })

  /** Compute and write the status document. */
  const publish = () => {
    const scope = runtime.statusScope
    if (scope === undefined) return
    // Teardown disposes the settings namespace around the same time our fiber's
    // drain runs, so a publish from a pass that outlived its services is
    // expected to fail. Once we have been told to stop, the status document is
    // not worth a warning.
    if (runtime.disposed) return
    const current = resolveConfig() ?? {}
    const limit = Number.isFinite(current.historyLimit) ? current.historyLimit : 20

    const areas = configuredAreas().map((area) => {
      const observed = runtime.areas.get(area.id)
      const problem = folderProblem(area.path)
      if (problem !== undefined) {
        return { id: area.id, status: 'error', at: Date.now(), detail: problem, head: '', ahead: 0, behind: 0 }
      }
      // `id` is restated last: an observed entry must never lose the field the
      // status schema requires, or the whole document would be rejected.
      return { ...(observed ?? { status: 'idle', at: 0, detail: '', head: '', ahead: 0, behind: 0 }), id: area.id }
    })

    runtime.revision += 1
    void scope.replace({
      revision: runtime.revision,
      running: runtime.running,
      updatedAt: Date.now(),
      areas,
      history: runtime.history.slice(-Math.max(1, limit)),
    }).catch((error) => {
      warn(`status publish failed: ${error instanceof Error ? error.message : String(error)}`)
    })
  }

  /** Resolve one area's credential value through the credentials seam. */
  const resolveCredential = async (ref) => {
    if (typeof ref !== 'string' || ref === '') return undefined
    const credentials = ctx.get('credentials')
    if (credentials === undefined) return undefined
    try {
      const hit = await credentials.resolve(ref)
      return hit === undefined ? undefined : hit.value
    } catch (error) {
      warn(`credential "${ref}" could not be resolved: ${error instanceof Error ? error.message : String(error)}`)
      return undefined
    }
  }

  /** Run one sync pass over the selected areas, publishing as it goes. */
  const runPass = async (options = {}) => {
    const current = resolveConfig() ?? {}
    const wanted = Array.isArray(options.areaIds) && options.areaIds.length > 0
      ? new Set(options.areaIds)
      : undefined
    const selected = configuredAreas().filter((area) => {
      if (area.enabled === false) return false
      if (wanted !== undefined) return wanted.has(area.id)
      if (typeof options.areaId === 'string' && options.areaId !== '') return area.id === options.areaId
      return true
    })

    runtime.running = true
    publish()
    try {
      for (const area of selected) {
        if (runtime.disposed) return
        const problem = folderProblem(area.path)
        if (problem !== undefined) {
          runtime.areas.set(area.id, { id: area.id, status: 'error', at: Date.now(), detail: problem, head: '', ahead: 0, behind: 0 })
          publish()
          continue
        }
        runtime.areas.set(area.id, { id: area.id, status: 'syncing', at: Date.now(), detail: '同步中…', head: '', ahead: 0, behind: 0 })
        publish()

        // Keep the repository self-describing before the commit, so the
        // manifest travels with the folder to the next machine.
        try {
          writeManifest(area.path, area)
        } catch (error) {
          warn(`manifest write failed for "${area.path}": ${error instanceof Error ? error.message : String(error)}`)
        }

        const credential = await resolveCredential(area.credentialRef)
        runtime.sessions.delete(area.id)
        let result
        try {
          result = await engine.syncArea({
            area,
            config: current,
            credential,
            turn: options.turn ?? 0,
            signal: options.signal,
            // Session records travel with the folder: they are written before
            // the commit so they are published by it, and read after the merge
            // so they see what the other machine published.
            hooks: {
              beforeCommit: (target) => runSessionStep('export', target, options.signal),
              afterIntegrate: (target) => runSessionStep('import', target, options.signal),
            },
          })
        } catch (error) {
          result = {
            id: area.id,
            status: 'error',
            detail: `同步失败：${error instanceof Error ? error.message : String(error)}`,
            head: '',
            ahead: 0,
            behind: 0,
          }
        }

        const value = { ...result, id: area.id, at: Date.now() }
        runtime.areas.set(area.id, value)
        const name = area.name !== undefined && area.name !== '' ? area.name : area.path
        const sessionNotes = runtime.sessions.get(area.id)?.notes ?? []
        runtime.history.push({
          at: value.at,
          areaId: area.id,
          ok: value.status === 'ok',
          summary: `${name} · ${value.detail}${sessionNotes.length === 0 ? '' : ` · ${sessionNotes.slice(0, 2).join('；')}`}`,
        })
        publish()
      }
    } finally {
      runtime.running = false
      publish()
    }
  }

  /** Queue one pass behind whatever is already running. */
  const enqueuePass = (options = {}) => {
    const next = queue.then(() => runPass(options), () => runPass(options))
    queue = next.then(() => undefined, () => undefined)
    return next
  }

  /**
   * Turn-boundary coalescing: bursty or nested turns inside one window collapse
   * into a single queued pass.
   */
  const pending = { areas: new Set(), all: false, turn: 0, timer: undefined }

  const flushPending = () => {
    pending.timer = undefined
    const ids = [...pending.areas]
    const { all, turn } = pending
    pending.areas.clear()
    pending.all = false
    if (all) enqueuePass({ turn })
    else if (ids.length > 0) enqueuePass({ turn, areaIds: ids })
  }

  /**
   * Decide what a finished turn should sync: the areas whose folder contains the
   * session's working directory, or every area when the user asked for that.
   * @param session - the session the turn belonged to.
   * @param event - the `turn/end` payload.
   */
  const scheduleTurnSync = (session, event) => {
    const current = resolveConfig() ?? {}
    if (current.enabled === false || current.syncOnTurnEnd === false) return
    const areas = configuredAreas().filter(area => area.enabled !== false)
    if (areas.length === 0) return

    const cwd = session !== undefined && session.header !== undefined ? session.header.cwd : undefined
    const matched = typeof cwd === 'string' ? areas.filter(area => pathContains(area.path, cwd)) : []
    if (matched.length === 0) {
      if (current.syncAllOnTurnEnd !== true) return
      pending.all = true
    } else {
      for (const area of matched) pending.areas.add(area.id)
    }
    pending.turn = Number.isFinite(event?.data?.turn) ? event.data.turn : 0

    const delay = Number.isFinite(current.debounceMs) ? Math.max(0, current.debounceMs) : 5000
    if (pending.timer !== undefined) clearTimeout(pending.timer)
    pending.timer = setTimeout(flushPending, delay)
  }

  // Turn boundaries are durable session events; `session/event` listeners are
  // post-commit and fire-and-forget, so a slow or failing sync can never delay
  // or break the conversation.
  ctx.on('session/event', (session, event) => {
    if (event === undefined || event.type !== 'turn/end') return
    try {
      scheduleTurnSync(session, event)
    } catch (error) {
      warn(`turn scheduling failed: ${error instanceof Error ? error.message : String(error)}`)
    }
  })

  ctx.effect(function* () {
    // Keep the fiber alive across an in-flight pass, and stop accepting new work
    // the moment this plugin unloads.
    yield async () => {
      runtime.disposed = true
      if (pending.timer !== undefined) {
        clearTimeout(pending.timer)
        pending.timer = undefined
      }
      await queue
    }
  }, 'sync-tool: pass drain')

  ctx.inject(['settings'], (settingsCtx) => {
    const settings = settingsCtx.settings

    /**
     * Adopt a folder another machine already synced: read its portable manifest
     * and append a work area for this machine. Only the machine-independent
     * facts come from the manifest — path, id, enabled flag and credential
     * reference are decided here.
     * @param path - absolute folder the operator picked.
     */
    const importArea = async (path) => {
      if (typeof path !== 'string' || path.trim() === '') return
      const manifest = readManifest(path)
      if (manifest === undefined) {
        warn(`"${path}" has no ${MANIFEST_NAME}; nothing to import`)
        return
      }
      const current = configuredAreas()
      if (current.some(area => normalizePath(area.path) === normalizePath(path))) {
        warn(`"${path}" is already a configured work area`)
        return
      }
      const area = areaFromManifest(path, manifest, `imported-${Date.now().toString(36)}`)
      try {
        await settings.mutate(SYNC_NAMESPACE, [{ op: 'set', path: ['areas'], value: [...current, area] }])
        runtime.history.push({
          at: Date.now(),
          areaId: area.id,
          ok: true,
          summary: `已从 ${baseName(path)} 导入配置（远端 ${area.remote === '' ? '未设置' : area.remote}）`,
        })
      } catch (error) {
        warn(`import failed: ${error instanceof Error ? error.message : String(error)}`)
      }
      publish()
    }

    settings.installSection(ctx, SYNC_NAMESPACE, Config, config, {
      setSource: (current) => { resolveConfig = current },
      onChange: () => {
        const current = resolveConfig() ?? {}
        publish()
        const request = current.request ?? {}
        const token = Number.isFinite(request.token) ? Number(request.token) : 0
        // The first observation only records the baseline.
        if (runtime.seenRequestToken === -1) {
          runtime.seenRequestToken = token
          return
        }
        if (token === runtime.seenRequestToken) return
        runtime.seenRequestToken = token
        if (request.kind === 'sync' && current.enabled !== false) {
          enqueuePass({ areaId: typeof request.areaId === 'string' ? request.areaId : '' })
        } else if (request.kind === 'import') {
          void importArea(typeof request.areaId === 'string' ? request.areaId : '')
        }
      },
    })

    // The status namespace is Host-owned: published wholesale, never merged,
    // because `update` deep-merges and would splice lists element-wise.
    runtime.statusScope = settings.register(STATUS_NAMESPACE, StatusConfig, {
      base: { revision: 0, running: false, updatedAt: 0, areas: [], history: [] },
    })

    publish()

    if ((resolveConfig() ?? {}).enabled !== false && (resolveConfig() ?? {}).syncOnStartup === true) {
      enqueuePass({})
    }
  })

  console.log(`[sync-tool] host half loaded (namespaces "${SYNC_NAMESPACE}", "${STATUS_NAMESPACE}", sessions -> "${sessionSync.state.path}")`)
}

export { buildCommitMessage, GitEngine, SessionSync }
